"""Add uploaded_images to orientations

Revision ID: 004
Revises: 46fd0384cfdf
Create Date: 2025-12-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '46fd0384cfdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orientations', sa.Column('uploaded_images', postgresql.ARRAY(sa.String()), nullable=True))
    # Set default empty array for existing records
    op.execute("UPDATE orientations SET uploaded_images = '{}' WHERE uploaded_images IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orientations', 'uploaded_images')
    # ### end Alembic commands ###
