"""Add orientation_id to field_searches

Revision ID: 005
Revises: 004
Create Date: 2025-12-31 22:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_searches', sa.Column('orientation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'field_searches', 'orientations', ['orientation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'field_searches', type_='foreignkey')
    op.drop_column('field_searches', 'orientation_id')
    # ### end Alembic commands ###
