"""Add RBAC permissions to roles

Revision ID: 04fa3b14ce43
Revises: 006
Create Date: 2026-01-04 15:06:10.715734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '04fa3b14ce43'
down_revision = '006'
branch_labels = None
depends_on = None

# Predefined roles with permissions
from app.core.permissions import PREDEFINED_ROLES


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Remove parent_role_id column (no longer needed)
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    indexes = [idx['name'] for idx in inspector.get_indexes('roles')]
    if 'ix_roles_parent_role_id' in indexes:
        op.drop_index('ix_roles_parent_role_id', table_name='roles')

    foreign_keys = inspector.get_foreign_keys('roles')
    for fk in foreign_keys:
        if fk['name'] == 'roles_parent_role_id_fkey':
            op.drop_constraint('roles_parent_role_id_fkey', 'roles', type_='foreignkey')

    columns = [col['name'] for col in inspector.get_columns('roles')]
    if 'parent_role_id' in columns:
        op.drop_column('roles', 'parent_role_id')

    # Step 2: Add new columns as NULLABLE first
    if 'display_name' not in columns:
        op.add_column('roles', sa.Column('display_name', sa.String(length=100), nullable=True))
    if 'permissions' not in columns:
        op.add_column('roles', sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True))
    if 'is_system' not in columns:
        op.add_column('roles', sa.Column('is_system', sa.Boolean(), nullable=True))

    # Step 3: Update existing roles with default values
    conn.execute(text("""
        UPDATE roles
        SET display_name = name,
            permissions = ARRAY[]::varchar[],
            is_system = FALSE
        WHERE display_name IS NULL
    """))

    # Step 4: Make admin role system role and give it all permissions
    conn.execute(text("""
        UPDATE roles
        SET is_system = TRUE
        WHERE name = 'admin'
    """))

    # Step 5: Insert predefined roles if they don't exist
    for role_name, role_data in PREDEFINED_ROLES.items():
        result = conn.execute(text("SELECT id FROM roles WHERE name = :name"), {"name": role_name})
        if not result.fetchone():
            # Insert new role
            permissions_array = "{" + ",".join(f'"{p}"' for p in role_data['permissions']) + "}"
            conn.execute(text("""
                INSERT INTO roles (name, display_name, description, permissions, is_system)
                VALUES (:name, :display_name, :description, :permissions, :is_system)
            """), {
                "name": role_data['name'],
                "display_name": role_data['display_name'],
                "description": role_data['description'],
                "permissions": permissions_array,
                "is_system": role_data['is_system']
            })
        else:
            # Update existing role with permissions
            permissions_array = "{" + ",".join(f'"{p}"' for p in role_data['permissions']) + "}"
            conn.execute(text("""
                UPDATE roles
                SET display_name = :display_name,
                    description = :description,
                    permissions = :permissions,
                    is_system = :is_system
                WHERE name = :name
            """), {
                "name": role_data['name'],
                "display_name": role_data['display_name'],
                "description": role_data['description'],
                "permissions": permissions_array,
                "is_system": role_data['is_system']
            })

    # Step 6: Make columns NOT NULL now that they have values
    op.alter_column('roles', 'display_name', nullable=False)
    op.alter_column('roles', 'permissions', nullable=False)
    op.alter_column('roles', 'is_system', nullable=False)

    # Step 7: Update description column length
    op.alter_column('roles', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('parent_role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_parent_role_id_fkey', 'roles', 'roles', ['parent_role_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_roles_parent_role_id', 'roles', ['parent_role_id'], unique=False)
    op.alter_column('roles', 'description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('roles', 'is_system')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'display_name')
    # ### end Alembic commands ###
