"""Add grid parameters to field searches

Revision ID: 1b78c9d580ac
Revises: c4834bdc794f
Create Date: 2025-12-26 23:05:19.410292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b78c9d580ac'
down_revision = 'c4834bdc794f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding them
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('field_searches')]

    if 'grid_center_lat' not in columns:
        op.add_column('field_searches', sa.Column('grid_center_lat', sa.Float(), nullable=True))
    if 'grid_center_lon' not in columns:
        op.add_column('field_searches', sa.Column('grid_center_lon', sa.Float(), nullable=True))
    if 'grid_cols' not in columns:
        op.add_column('field_searches', sa.Column('grid_cols', sa.Integer(), nullable=True))
    if 'grid_rows' not in columns:
        op.add_column('field_searches', sa.Column('grid_rows', sa.Integer(), nullable=True))
    if 'grid_cell_size' not in columns:
        op.add_column('field_searches', sa.Column('grid_cell_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('field_searches', 'grid_cell_size')
    op.drop_column('field_searches', 'grid_rows')
    op.drop_column('field_searches', 'grid_cols')
    op.drop_column('field_searches', 'grid_center_lon')
    op.drop_column('field_searches', 'grid_center_lat')
    # ### end Alembic commands ###
