"""Add basis and notes fields to cases

Revision ID: 46fd0384cfdf
Revises: 1b78c9d580ac
Create Date: 2025-12-27 15:11:30.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46fd0384cfdf'
down_revision = '1b78c9d580ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('basis', sa.String(length=200), nullable=True))
    op.add_column('cases', sa.Column('notes_text', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('notes_images', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'notes_images')
    op.drop_column('cases', 'notes_text')
    op.drop_column('cases', 'basis')
    # ### end Alembic commands ###
