"""Add organizations table

Revision ID: a69b47b530bc
Revises: 007_add_videos
Create Date: 2026-01-21 23:11:29.047856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69b47b530bc'
down_revision = '007_add_videos'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
