"""Add police fields to cases

Revision ID: c4834bdc794f
Revises: 003
Create Date: 2025-12-26 13:28:14.390621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4834bdc794f'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('police_report_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('cases', sa.Column('police_department', sa.String(length=200), nullable=True))
    op.add_column('cases', sa.Column('police_contact_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cases', 'users', ['police_contact_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_events_created_by', table_name='events')
    op.drop_index('idx_events_search_id', table_name='events')
    op.drop_index('idx_events_updated_by', table_name='events')
    op.drop_index('idx_flyer_templates_template_type', table_name='flyer_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_flyer_templates_template_type', 'flyer_templates', ['template_type'], unique=False)
    op.create_index('idx_events_updated_by', 'events', ['updated_by_user_id'], unique=False)
    op.create_index('idx_events_search_id', 'events', ['search_id'], unique=False)
    op.create_index('idx_events_created_by', 'events', ['created_by_user_id'], unique=False)
    op.drop_constraint(None, 'cases', type_='foreignkey')
    op.drop_column('cases', 'police_contact_user_id')
    op.drop_column('cases', 'police_department')
    op.drop_column('cases', 'police_report_date')
    # ### end Alembic commands ###
